<?php
declare(strict_types=1);
require_once __DIR__ . '/../../../config/database.php'; require_once __DIR__ . '/../../../config/session.php'; require_once __DIR__ . '/../../models/Usuario.php'; require_once __DIR__ . '/../../services/AuthService.php'; require_once __DIR__ . '/../../controllers/AuthController.php'; require_once __DIR__ . '/../../helpers/seguranca.php';
iniciar_sessao_segura(); $controller = new AuthController(new AuthService(new Usuario($pdo))); $erros = []; $dados = ['nome' => '', 'email' => ''];
if ($_SERVER['REQUEST_METHOD'] === 'POST') { if (!validar_token_csrf($_POST['csrf_token'] ?? null)) $erros['geral'] = 'A sessão do formulário expirou. Tente novamente.'; else { $resultado = $controller->cadastrar($_POST); $erros = $resultado['erros']; $dados = $resultado['dados'] ?: $dados; if ($resultado['sucesso']) { header('Location: login.php?msg=sucesso_cadastro'); exit; } } }
?><!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Cadastro - Portal SI</title><link rel="stylesheet" href="../../../public/assets/css/style.css?v=<?= e(substr((string) hash_file('sha256', __DIR__ . '/../../../public/assets/css/style.css'), 0, 12)) ?>"></head><body>
<div class="site-topbar">Faculdades ESUCRI · Portal de Comunicação SI</div><header class="site-header"><div class="site-header__inner"><a class="brand" href="login.php"><span class="brand__mark">e</span><span><span class="brand__name">ESUCRI</span><span class="brand__sub">PORTAL DE COMUNICAÇÃO SI</span></span></a></div></header>
<main class="page-shell"><section class="auth-card"><p class="auth-card__eyebrow">Acesso acadêmico</p><h1>Criar conta</h1><p class="auth-card__intro">Cadastre-se para acompanhar as informações do curso de Sistemas de Informação.</p><?php if (!empty($erros)): ?><div class="message" role="alert"><ul><?php foreach ($erros as $erro): ?><li><?= e($erro) ?></li><?php endforeach; ?></ul></div><?php endif; ?>
<form method="post" action="cadastro.php"><input type="hidden" name="csrf_token" value="<?= e(obter_token_csrf()) ?>"><div class="form-group"><label for="nome">Nome completo</label><input id="nome" name="nome" type="text" required minlength="3" value="<?= e($dados['nome']) ?>"></div><div class="form-group"><label for="email">E-mail</label><input id="email" name="email" type="email" required value="<?= e($dados['email']) ?>"></div><div class="form-group"><label for="senha">Senha</label><input id="senha" name="senha" type="password" required minlength="8"></div><div class="form-group"><label for="confirmar_senha">Confirmar senha</label><input id="confirmar_senha" name="confirmar_senha" type="password" required minlength="8"></div><button type="submit">Cadastrar</button></form><p class="form-links"><a href="login.php">Já tenho uma conta</a></p></section></main>
<footer class="site-footer"><div class="site-footer__inner"><p>ESUCRI · Criciúma - SC</p><p>Portal de Comunicação SI</p></div></footer></body></html>
